trigger:
- main # Trigger the pipeline for changes in the `main` branch

pool:
  vmImage: 'windows-latest' # Use an Ubuntu virtual machine for the build process

steps:
# Step 1: Checkout the repository code
- task: Checkout@1
  displayName: 'Checkout source code'

# Step 2: Publish the HTML file as an artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish index.html as a pipeline artifact'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/index.html' # Path to index.html in the repo
    artifact: 'html_artifact' # Name of the artifact
