trigger:
- main # Trigger the pipeline on changes to the main branch

pool:
  name: 'SelfHostedPool' # Name of your self-hosted agent pool
  demands:
  - Agent.OS -equals Windows_NT # Ensure the pipeline runs on a Windows agent

steps:
# Step 1: Checkout the repository
- task: Checkout@1
  displayName: 'Checkout source code'

# Step 2: Publish the HTML file
- task: PublishPipelineArtifact@1
  displayName: 'Publish index.html as a pipeline artifact'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/content/index.html'# Path to index.html
    artifact: 'html_artifact' # Name of the artifact
