trigger:
- main

pool:
  name: 'SelfHostedPool' # Use the actual name of your self-hosted agent pool

steps:
# Step 1: Checkout the repository
- checkout: self
  displayName: 'Checkout source code'

# Step 2: Publish the HTML file
- task: PublishPipelineArtifact@1
  displayName: 'Publish index.html as a pipeline artifact'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/index.html' # Path to index.html
    artifact: 'html_artifact' # Name of the artifact
